# Generated by Django 3.2 on 2025-05-07 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='emp',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='emp',
            name='img',
            field=models.ImageField(default='', upload_to='employee/'),
        ),
        migrations.AddField(
            model_name='emp',
            name='join_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='emp',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
