# Generated by Django 3.2 on 2025-05-07 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_client_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, verbose_name='Client ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('pay', models.CharField(max_length=100, verbose_name='How many videos')),
                ('pending', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Who withdraw')),
                ('purpose', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
            ],
            options={
                'verbose_name': 'Withdraw',
                'verbose_name_plural': 'Withdraws',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='photo',
            field=models.CharField(max_length=100, verbose_name='How many photos'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video',
            field=models.CharField(max_length=100, verbose_name='How many videos'),
        ),
    ]
