# Generated by Django 3.2 on 2025-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_deposit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposit'},
        ),
        migrations.AddField(
            model_name='emp',
            name='employee_id',
            field=models.CharField(blank=True, default=' ', max_length=10, unique=True),
        ),
    ]
