# Generated by Django 3.2 on 2025-05-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20250507_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=' ', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='employee_id',
            field=models.CharField(blank=True, default=' ', editable=False, max_length=10, unique=True),
        ),
    ]
