# Generated by Django 3.2 on 2025-05-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
