# Generated by Django 3.2 on 2025-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_client_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
