# Generated by Django 5.2 on 2025-05-09 05:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_emp_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('project_name', models.CharField(max_length=100, verbose_name='Project Name')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='Start Date')),
                ('is_active', models.BooleanField(blank=True, default=True, editable=False, null=True)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.client', verbose_name='Client Name')),
                ('work_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.emp', verbose_name='Work On')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
