# Generated by Django 5.2 on 2025-05-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_withdraw_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='pay',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='pending',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
