# Generated by Django 3.2 on 2025-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20250512_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='employee_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
