# Generated by Django 3.2 on 2025-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20250512_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='emp',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='emp',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='emp',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='emp',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='emp',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
