# Generated by Django 5.2 on 2025-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_emp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='user',
        ),
        migrations.AddField(
            model_name='emp',
            name='employee_pass',
            field=models.CharField(blank=True, default='', editable=False, max_length=10, unique=True),
        ),
    ]
