# Generated by Django 5.2 on 2025-05-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_emp_user_emp_employee_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='employee_pass',
            field=models.CharField(blank=True, default='password', editable=False, max_length=10, unique=True),
        ),
    ]
